/* Auto-generated by gen_fight_msgs.py -- do not edit */
#ifndef FIGHT_MSGS_H
#define FIGHT_MSGS_H
#include <stdint.h>

extern const uint8_t ft_vs[6];
extern const uint8_t ft_npc_msg[9];
extern const uint8_t ft_npc_msg2[12];
extern const uint8_t ft_npc_msg3[12];
extern const uint8_t ft_man_msg[38];
extern const uint8_t ft_man_msg2[23];
extern const uint8_t ft_man_msg3[10];
extern const uint8_t ft_man_msg4[20];
extern const uint8_t ft_man_msg5[23];
extern const uint8_t ft_man_msg6[45];
extern const uint8_t ft_man_msg7[16];
extern const uint8_t ft_boss_msg[89];
extern const uint8_t ft_boss_msg2[167];
extern const uint8_t ft_boss_msg3[138];
extern const uint8_t ft_not_move_msg0[17];
extern const uint8_t ft_not_move_msg1[17];
extern const uint8_t ft_not_move_msg2[36];
extern const uint8_t ft_fenshen_dodge_msg[50];
extern const uint8_t ft_damage0_msg[18];
extern const uint8_t ft_result_tip[5];
extern const uint8_t ft_parry1_msg[30];
extern const uint8_t ft_parry2_msg[28];
extern const uint8_t ft_parry3_msg[24];
extern const uint8_t ft_parry4_msg[32];
extern const uint8_t ft_unarmed1_parry[16];
extern const uint8_t ft_unarmed2_parry[16];
extern const uint8_t ft_status100_msg[28];
extern const uint8_t ft_status95_msg[30];
extern const uint8_t ft_status90_msg[20];
extern const uint8_t ft_status80_msg[26];
extern const uint8_t ft_status60_msg[30];
extern const uint8_t ft_status40_msg[30];
extern const uint8_t ft_status30_msg[28];
extern const uint8_t ft_status20_msg[22];
extern const uint8_t ft_status10_msg[28];
extern const uint8_t ft_status0_msg[20];
extern const uint8_t ft_eff_status100_msg[28];
extern const uint8_t ft_eff_status95_msg[30];
extern const uint8_t ft_eff_status90_msg[22];
extern const uint8_t ft_eff_status80_msg[30];
extern const uint8_t ft_eff_status60_msg[30];
extern const uint8_t ft_eff_status40_msg[30];
extern const uint8_t ft_eff_status30_msg[28];
extern const uint8_t ft_eff_status20_msg[28];
extern const uint8_t ft_eff_status10_msg[22];
extern const uint8_t ft_eff_status5_msg[26];
extern const uint8_t ft_eff_status0_msg[26];
extern const uint8_t ft_t0damage10_msg[26];
extern const uint8_t ft_t0damage20_msg[20];
extern const uint8_t ft_t0damage40_msg[18];
extern const uint8_t ft_t0damage80_msg[24];
extern const uint8_t ft_t0damage120_msg[24];
extern const uint8_t ft_t0damage160_msg[24];
extern const uint8_t ft_t0damage240_msg[24];
extern const uint8_t ft_t0damagebig_msg[28];
extern const uint8_t ft_t1damage10_msg[22];
extern const uint8_t ft_t1damage20_msg[20];
extern const uint8_t ft_t1damage40_msg[18];
extern const uint8_t ft_t1damage80_msg[26];
#define ft_t1damage120_msg ft_t1damage160_msg
extern const uint8_t ft_t1damage160_msg[28];
#define ft_t1damage240_msg ft_t1damagebig_msg
extern const uint8_t ft_t1damagebig_msg[32];
extern const uint8_t ft_t2damage10_msg[20];
extern const uint8_t ft_t2damage20_msg[22];
extern const uint8_t ft_t2damage40_msg[16];
extern const uint8_t ft_t2damage80_msg[16];
#define ft_t2damage120_msg ft_t2damage160_msg
extern const uint8_t ft_t2damage160_msg[24];
#define ft_t2damage240_msg ft_t2damagebig_msg
extern const uint8_t ft_t2damagebig_msg[29];
extern const uint8_t ft_t3damage10_msg[18];
extern const uint8_t ft_t3damage20_msg[24];
extern const uint8_t ft_t3damage40_msg[30];
extern const uint8_t ft_t3damage80_msg[30];
extern const uint8_t ft_t3damage120_msg[26];
extern const uint8_t ft_t3damage160_msg[28];
extern const uint8_t ft_t3damage240_msg[28];
extern const uint8_t ft_t3damagebig_msg[32];
extern const uint8_t ft_t4damage10_msg[22];
extern const uint8_t ft_t4damage20_msg[18];
extern const uint8_t ft_t4damage40_msg[24];
extern const uint8_t ft_t4damage80_msg[30];
extern const uint8_t ft_t4damage120_msg[34];
extern const uint8_t ft_t4damage160_msg[25];
extern const uint8_t ft_t4damage240_msg[34];
extern const uint8_t ft_t4damagebig_msg[32];
extern const uint8_t ft_t5damage10_msg[20];
extern const uint8_t ft_t5damage20_msg[24];
extern const uint8_t ft_t5damage40_msg[24];
extern const uint8_t ft_t5damage80_msg[28];
extern const uint8_t ft_t5damage120_msg[25];
extern const uint8_t ft_t5damage160_msg[30];
extern const uint8_t ft_t5damage240_msg[36];
extern const uint8_t ft_t5damagebig_msg[34];

extern const uint8_t ft_img_hp[18];
extern const uint8_t ft_img_fp[18];
extern const uint8_t ft_img_exp_ball[34];

extern const uint8_t *const ft_dead_talk[5];
extern const uint8_t *const ft_boss_tbl[3];
extern const uint8_t *const *const ft_damage_msg_tbl[6];
extern const uint8_t *const ft_status_msg_tbl[11];
extern const uint8_t *const ft_eff_status_tbl[11];
extern const uint8_t *const ft_parry_msg_tbl[4];
extern const uint8_t *const ft_unarmed_parry_tbl[2];
extern const uint8_t ft_damage_msg_data[8];
extern const uint8_t ft_status_msg_data[11];

#endif
