/* Auto-generated by gen_task_msgs.py -- do not edit */
#ifndef TASK_MSGS_H
#define TASK_MSGS_H
#include <stdint.h>

extern const uint8_t tm_good_man_msg[34];
#define TM_GOOD_MAN_MSG_LEN 34
extern const uint8_t tm_bad_man_msg[31];
#define TM_BAD_MAN_MSG_LEN 31
extern const uint8_t tm_no_npc_msg[29];
#define TM_NO_NPC_MSG_LEN 29
extern const uint8_t tm_npc_new_msg[15];
#define TM_NPC_NEW_MSG_LEN 15
extern const uint8_t tm_goods_new_msg[38];
#define TM_GOODS_NEW_MSG_LEN 38
extern const uint8_t tm_kill_new_msg[38];
#define TM_KILL_NEW_MSG_LEN 38
extern const uint8_t tm_npc_exist_msg[27];
#define TM_NPC_EXIST_MSG_LEN 27
extern const uint8_t tm_goods_exist_msg[21];
#define TM_GOODS_EXIST_MSG_LEN 21
extern const uint8_t tm_kill_exist_msg[23];
#define TM_KILL_EXIST_MSG_LEN 23
extern const uint8_t tm_quest_done_msg[32];
#define TM_QUEST_DONE_MSG_LEN 32
extern const uint8_t tm_quest_reward_msg[38];
#define TM_QUEST_REWARD_MSG_LEN 38
extern const uint8_t tm_if_give_msg[19];
#define TM_IF_GIVE_MSG_LEN 19
extern const uint8_t tm_no_bonus_msg[18];
#define TM_NO_BONUS_MSG_LEN 18
extern const uint8_t tm_gnot_done_msg[28];
#define TM_GNOT_DONE_MSG_LEN 28
#define TM_GNOT_DONE_MSG_S0 19	/* dw task_temp1 */
extern const uint8_t tm_kill_npc_msg[51];
#define TM_KILL_NPC_MSG_LEN 51
#define TM_KILL_NPC_MSG_S0 11	/* dw quest_exp */
#define TM_KILL_NPC_MSG_S1 20	/* dw a9 */
extern const uint8_t tm_bonus_msg[44];
#define TM_BONUS_MSG_LEN 44
#define TM_BONUS_MSG_S0 14	/* dw task_buf+2 */
#define TM_BONUS_MSG_S1 31	/* dw task_buf+4 */
extern const uint8_t tm_get_pot_msg[27];
#define TM_GET_POT_MSG_LEN 27
#define TM_GET_POT_MSG_S0 14	/* dw task_buf+4 */
extern const uint8_t tm_get_exp_msg[31];
#define TM_GET_EXP_MSG_LEN 31
#define TM_GET_EXP_MSG_S0 14	/* dw task_buf+2 */
extern const uint8_t tm_time_limit_msg[39];
#define TM_TIME_LIMIT_MSG_LEN 39
extern const uint8_t tm_voluntary_task_msg[41];
#define TM_VOLUNTARY_TASK_MSG_LEN 41
#define TM_VOLUNTARY_TASK_MSG_S0 30	/* dw task_temp1 */
extern const uint8_t tm_exp_high_msg[46];
#define TM_EXP_HIGH_MSG_LEN 46
extern const uint8_t tm_have_task_msg[25];
#define TM_HAVE_TASK_MSG_LEN 25
extern const uint8_t tm_name_xing_tbl[16];
#define TM_NAME_XING_TBL_LEN 16
extern const uint8_t tm_name_ming_tbl[16];
#define TM_NAME_MING_TBL_LEN 16
extern const uint8_t tm_random_task[12];
#define TM_RANDOM_TASK_LEN 12
extern const uint8_t tm_work_bonus_msg[54];
#define TM_WORK_BONUS_MSG_LEN 54
#define TM_WORK_BONUS_MSG_S0 13	/* dw varbuf+2 */
#define TM_WORK_BONUS_MSG_S1 30	/* dw varbuf+4 */
#define TM_WORK_BONUS_MSG_S2 43	/* dw varbuf+6 */
extern const uint8_t tm_saodi_msg[64];
#define TM_SAODI_MSG_LEN 64
extern const uint8_t tm_tiaoshui_msg[64];
#define TM_TIAOSHUI_MSG_LEN 64
extern const uint8_t tm_pichai_msg[64];
#define TM_PICHAI_MSG_LEN 64
extern const uint8_t tm_over_msg[25];
#define TM_OVER_MSG_LEN 25
extern const uint8_t tm_fail_msg[36];
#define TM_FAIL_MSG_LEN 36
extern const uint8_t tm_diao_gan_msg[68];
#define TM_DIAO_GAN_MSG_LEN 68
extern const uint8_t tm_fish_hp_msg[51];
#define TM_FISH_HP_MSG_LEN 51
extern const uint8_t tm_fish_start_msg[103];
#define TM_FISH_START_MSG_LEN 103
extern const uint8_t tm_no_fish_msg[49];
#define TM_NO_FISH_MSG_LEN 49
extern const uint8_t tm_have_fish_msg[44];
#define TM_HAVE_FISH_MSG_LEN 44
extern const uint8_t tm_fish_escape_msg[83];
#define TM_FISH_ESCAPE_MSG_LEN 83
extern const uint8_t tm_fish_suc_msg[51];
#define TM_FISH_SUC_MSG_LEN 51
extern const uint8_t tm_drink_fail_msg[26];
#define TM_DRINK_FAIL_MSG_LEN 26
extern const uint8_t tm_drink_succ_msg[32];
#define TM_DRINK_SUCC_MSG_LEN 32
extern const uint8_t tm_find_rope_msg[10];
#define TM_FIND_ROPE_MSG_LEN 10
extern const uint8_t tm_sleep_msg[17];
#define TM_SLEEP_MSG_LEN 17
extern const uint8_t tm_find_bao_msg[14];
#define TM_FIND_BAO_MSG_LEN 14
extern const uint8_t tm_rope_msg[37];
#define TM_ROPE_MSG_LEN 37
extern const uint8_t tm_suicide_msg[58];
#define TM_SUICIDE_MSG_LEN 58
extern const uint8_t tm_board1_msg[14];
#define TM_BOARD1_MSG_LEN 14
extern const uint8_t tm_board2_msg[23];
#define TM_BOARD2_MSG_LEN 23
#define TM_BOARD2_MSG_S0 15	/* dw varbuf */
extern const uint8_t tm_know_msg[20];
#define TM_KNOW_MSG_LEN 20
extern const uint8_t tm_pingding_msg[82];
#define TM_PINGDING_MSG_LEN 82
#define TM_PINGDING_MSG_S0 11	/* dw game_hour */
#define TM_PINGDING_MSG_S1 17	/* dw game_min */
#define TM_PINGDING_MSG_S2 32	/* dw npc_kill */
#define TM_PINGDING_MSG_S3 47	/* dw do_kill */
#define TM_PINGDING_MSG_S4 62	/* dw man_daode */
#define TM_PINGDING_MSG_S5 77	/* dw rank_desc */
extern const uint8_t tm_rank1_msg[10];
#define TM_RANK1_MSG_LEN 10
extern const uint8_t tm_rank2_msg[10];
#define TM_RANK2_MSG_LEN 10
extern const uint8_t tm_rank3_msg[10];
#define TM_RANK3_MSG_LEN 10
extern const uint8_t tm_rank4_msg[10];
#define TM_RANK4_MSG_LEN 10
extern const uint8_t tm_rank5_msg[10];
#define TM_RANK5_MSG_LEN 10
extern const uint8_t tm_rank6_msg[10];
#define TM_RANK6_MSG_LEN 10
extern const uint8_t tm_rank7_msg[10];
#define TM_RANK7_MSG_LEN 10
extern const uint8_t tm_rank8_msg[10];
#define TM_RANK8_MSG_LEN 10
extern const uint8_t tm_rank9_msg[10];
#define TM_RANK9_MSG_LEN 10
extern const uint8_t tm_rank10_msg[10];
#define TM_RANK10_MSG_LEN 10
extern const uint8_t tm_rank11_msg[10];
#define TM_RANK11_MSG_LEN 10
extern const uint8_t tm_rank_end1_msg[148];
#define TM_RANK_END1_MSG_LEN 148
extern const uint8_t tm_rank_end2_msg[199];
#define TM_RANK_END2_MSG_LEN 199
extern const uint8_t tm_hill_msg[56];
#define TM_HILL_MSG_LEN 56
extern const uint8_t tm_select_road_msg[75];
#define TM_SELECT_ROAD_MSG_LEN 75

#endif
